# Copyright 2024 Dynatrace LLC .
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- set_fact:
    dt_synthetic_node_id: ""
      
- name: ActiveGate - Get all Synthetic nodes
  when: activegate_install_synthetic
  block:
  - uri:
      url: "{{ dynatrace_tenant_url }}/api/v1/synthetic/nodes"
      method: GET
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ ace_box_activegate_installer_api_token }}"
      return_content: no
      status_code: 200, 201, 204
    register: nodes_response_raw
    until: "{{ (nodes_response_raw.json | json_query(synthetic_nodes_query) | length) > 0 }}"
    retries: 15
    delay: 10
  - set_fact:
      dt_synthetic_node_id: "{{ nodes_response_raw.json | json_query(synthetic_nodes_query) | first }}"
  rescue:
  - set_fact:
      dt_synthetic_node_id: ""

- name: Create namespace for ActiveGate Config
  become: true
  become_user: "{{ ace_box_user }}"
  kubernetes.core.k8s:
    name: "{{ activegate_config_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create activegate ConfigMap
  become: true
  become_user: "{{ ace_box_user }}"
  kubernetes.core.k8s:
    name: "synthetic-activegate"
    api_version: v1
    kind: ConfigMap
    state: present
    namespace: "{{ activegate_config_namespace }}"
    resource_definition:
      data:
        dt_synthetic_node_id: "{{ dt_synthetic_node_id }}"
