# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################
# Set ingress_class to traefik #
################################
- include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "ingress_class"
    var_value_to_set: "traefik"

- include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "kubernetes_flavour"
    var_value_to_set: "k3s"

- name: Ensures /etc/rancher/k3s dir exists
  become: true
  become_user: root
  file:
    path: "/etc/rancher/k3s"
    state: directory

- name: Template k3s kubelet.config
  become: true
  become_user: root
  ansible.builtin.template:
    src: kubelet.config.j2
    dest: "/etc/rancher/k3s/kubelet.config"
    mode: 0600

- name: Install k3s
  become: true
  become_user: root
  shell:
    cmd: 'curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--kubelet-arg=config=/etc/rancher/k3s/kubelet.config" sh -'

- name: pip install kubernetes
  become: true
  become_user: root
  shell:
    cmd: python3 -m pip install --break-system-packages kubernetes

- name: Create a directory if it does not exist
  become: true
  become_user: root
  ansible.builtin.file:
    path: /home/{{ ace_box_user }}/.kube
    state: directory

- name: copy kube config
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ace_box_user }}/.kube/config

- include_tasks: install-helm.yml

- include_role:
    name: docker

- include_role:
    name: private-registry

- include_tasks: configure-registry.yml

###############
# Restart k3s #
###############
- name: k3s restart
  become: true
  become_user: root
  ansible.builtin.service:
    name: k3s
    state: restarted
