# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_role:
    name: k3s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- include_role:
    name: dt-operator
  vars:
    dt_operator_release: "v1.2.3"
    operator_mode: "classicFullStack" 

- include_role:
    name: monaco-v2

- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "monaco_cleanup_api_token"
    access_token_scope:
      [
        "slo.read",
        "slo.write",
        "CaptureRequestData",
        "credentialVault.read",
        "credentialVault.write",
        "DataExport",
        "DataPrivacy",
        "ExternalSyntheticIntegration",
        "ReadConfig",
        "WriteConfig",
        "events.ingest",
        "settings.read",
        "settings.write",
        "metrics.ingest",
        "openTelemetryTrace.ingest",
        "logs.ingest",
      ]

- set_fact:
    demo_rel_val_release_stage: "simplenode-gitlab-staging"
    demo_rel_val_release_product: "simplenodeservice"
    demo_rel_val_identifier: "{{ demo_identifier }}"

# - name: Template Helm values file
#   ansible.builtin.template:
#     src: "{{ role_path }}/files/monaco/templates/delete-app.yaml.j2"
#     dest: "{{ role_path }}/files/monaco/delete-app-staging.yaml"
#     owner: "{{ ace_box_user }}"
#     group: "{{ ace_box_user }}"
#     mode: '0644'

# - set_fact:
#     demo_rel_val_release_stage: "simplenode-gitlab-prod"

# - name: Template Helm values file
#   ansible.builtin.template:
#     src: "{{ role_path }}/files/monaco/templates/delete-app.yaml.j2"
#     dest: "{{ role_path }}/files/monaco/delete-app-production.yaml"
#     owner: "{{ ace_box_user }}"
#     group: "{{ ace_box_user }}"
#     mode: '0644'

# - name: Template Helm values file
#   ansible.builtin.template:
#     src: "{{ role_path }}/files/monaco/templates/delete-infra.yaml.j2"
#     dest: "{{ role_path }}/files/monaco/delete-infra.yaml"
#     owner: "{{ ace_box_user }}"
#     group: "{{ ace_box_user }}"
#     mode: '0644'

# - set_fact:
#     monaco_projects_folder: "{{ role_path }}/files/monaco"

# - name: Monaco - Delete Config App Staging
#   include_role:
#     name: monaco-v2
#     tasks_from: delete-monaco
#   vars:
#     monaco_manifest_path: "{{ monaco_projects_folder }}/manifest.yaml"
#     monaco_delete_path: "{{ monaco_projects_folder }}/delete-app-staging.yaml"
#     monaco_environment:
#       DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
#       DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
#       DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
#       DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
#       DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"

# - name: Monaco - Delete Config App Prod
#   include_role:
#     name: monaco-v2
#     tasks_from: delete-monaco
#   vars:
#     monaco_manifest_path: "{{ monaco_projects_folder }}/manifest.yaml"
#     monaco_delete_path: "{{ monaco_projects_folder }}/delete-app-production.yaml"
#     monaco_environment:
#       DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
#       DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
#       DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
#       DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
#       DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"

# - name: Monaco - Delete Config Infra
#   include_role:
#     name: monaco-v2
#     tasks_from: delete-monaco
#   vars:
#     monaco_manifest_path: "{{ monaco_projects_folder }}/manifest.yaml"
#     monaco_delete_path: "{{ monaco_projects_folder }}/delete-infra.yaml"
#     monaco_environment:
#       DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}"
#       DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
#       DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
#       DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
#       DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"

- include_role:
    name: otel-collector

- name: Source Otel Collector endpoint
  include_role:
    name: otel-collector
    tasks_from: source-endpoints

- include_role:
    name: gitlab

- name: Gitlab - Ensure Group
  include_role:
    name: gitlab
    tasks_from: ensure-group
  vars:
    gitlab_group_name: "{{ gitlab_demo_srg_group }}"

- name: Gitlab - Ensure Default Group Vars
  include_role:
    name: gitlab
    tasks_from: ensure-default-group-vars
  vars:
    gitlab_group_name: "{{ gitlab_demo_srg_group }}"

- name: Gitlab - Ensure Project
  include_role:
    name: gitlab
    tasks_from: ensure-project
  vars:
    gitlab_prj: "{{ gitlab_demo_srg_repo_name }}"
    gitlab_prj_namespace_id: "{{ gitlab_group_id }}"

- set_fact:
    demo_srg_gitlab_project_id: "{{ gitlab_project_id }}"

- include_role:
    name: gitlab
    tasks_from: source-endpoints-external
  when: gitlab_external_endpoint is not defined

- include_role:
    name: gitlab
    tasks_from: source-secret
  when: gitlab_personal_access_token is not defined or gitlab_username is not defined or gitlab_password is not defined

- name: Gitlab - Additional Environment Variables
  include_role:
    name: gitlab
    tasks_from: ensure-group-var
  vars:
    gitlab_var_key: "{{ item.key }}"
    gitlab_var_value: "{{ item.value }}"
  loop:
    - {
        key: "DT_PLATFORM_TENANT_URL",
        value: "{{ extra_vars.dt_environment_url_gen3.rstrip('/') }}",
      }
    - {
        key: "DT_OAUTH_CLIENT_ID",
        value: "{{ extra_vars.dt_oauth_client_id }}",
      }
    - {
        key: "DT_OAUTH_CLIENT_SECRET",
        value: "{{ extra_vars.dt_oauth_client_secret }}",
      }
    - {
        key: "DT_OAUTH_SSO_ENDPOINT",
        value: "{{ extra_vars.dt_oauth_sso_endpoint.rstrip('/') }}",
      }
    - {
        key: "DT_OAUTH_ACCOUNT_URN",
        value: "{{ extra_vars.dt_oauth_account_urn }}",
      }
    - { key: "GITLAB_USERNAME", value: "{{ gitlab_username }}" }
    - { key: "GITLAB_PASSWORD", value: "{{ gitlab_password }}" }
    - {
        key: "GITLAB_PRIVATE_TOKEN",
        value: "{{ gitlab_personal_access_token }}",
      }
    - {
        key: "GITLAB_EXTERNAL_ENDPOINT",
        value: "{{ gitlab_external_endpoint }}",
      }
    - { key: "DEMO_IDENTIFIER", value: "{{ demo_identifier }}" }
    - {
        key: "OTEL_EXPORTER_OTEL_ENDPOINT",
        value: "{{ otel_internal_endpoint }}",
      }

- name: Source Gitlab endpoint
  include_role:
    name: gitlab
    tasks_from: source-endpoints

- set_fact:
    role_path_abs: "{{ role_path }}"

- include_role:
    name: app-simplenode
  vars:
    git_username: "root"
    git_password: "{{ gitlab_password }}"
    git_domain: "{{ gitlab_domain }}"
    git_endpoint: '{{ gitlab_internal_endpoint | regex_replace("http://") }}'
    git_org_name: "{{ gitlab_demo_srg_group }}"
    repo_name: "{{ gitlab_demo_srg_repo_name }}"
    app_simplenode_overwrites:
      # Ignores folders from being copied to the repo:
      - dest: demo/
      - dest: jenkins/
      - dest: jmeter/
      - dest: load-gen/
      - dest: cloudautomation/
      # Overwrites folders in the repo:
      - dest: monaco/
        src: "{{ role_path_abs }}/files/monaco/"
      - dest: locust/
        src: "{{ role_path_abs }}/files/locust/"
      - dest: docs/
        src: "{{ role_path_abs }}/files/docs/"
      # Overwrites files in the repo:
      - dest: .gitlab-ci.yml
        src: "{{ role_path_abs }}/files/.gitlab-ci.yml"
      - dest: dynatrace/dynatrace.attachrules.yaml
        src: "{{ role_path_abs }}/files/dynatrace.attachrules.yaml"
      - dest: otel-exporter.yml
        src: "{{ role_path_abs }}/files/otel-exporter.yml"

- name: Gitlab - Ensure Project for OpenTelemetry Metrics
  include_role:
    name: gitlab
    tasks_from: ensure-project
  vars:
    gitlab_prj: "{{ gitlab_demo_metrics_exporter_repo_name }}"
    gitlab_prj_namespace_id: "{{ gitlab_group_id }}"

- set_fact:
    dt_metrics_exporter_repo_src: "{{ role_path }}/files/metrics-exporter"

- name: Publish docs
  include_role:
    name: repository
  vars:
    git_username: "root"
    git_password: "{{ gitlab_password }}"
    git_domain: "{{ gitlab_domain }}"
    git_remote: "gitlab"
    git_org: "{{ gitlab_demo_srg_group }}"
    git_repo: "{{ gitlab_demo_metrics_exporter_repo_name }}"
    repo_src: "{{ dt_metrics_exporter_repo_src }}"
    track_upstream: true

- include_role:
    name: dashboard
  vars:
    include_dashboard_value_file: "{{ role_path_abs }}/templates/demo-release-validation-srg-gitlab-dashboard.yml.j2"

- set_fact:
    role_path_abs:

- include_tasks:
    file: health-check.yml
