# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "demo_auto_remediation_ansible"
    var_value_to_set: true

- include_role:
    name: microk8s

- include_role:
    name: dt-activegate-classic
  vars:
    activegate_install_synthetic: true

- include_role:
    name: dt-operator
  vars:
    dt_operator_release: "v1.2.3"
    operator_mode: "classicFullStack" 

- include_role:
    name: monaco

- include_role:
    name: gitea

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"
    gitea_repo: "{{ demo_auto_remediation_repo_name }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"
    gitea_repo: "{{ demo_auto_remediation_repo_name }}-docs"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_auto_remediation_org }}"
    gitea_repo: "{{ demo_auto_remediation_repo_name }}-awx"

- include_role:
    name: repository
  vars:
    repo_src: "{{ item.repo_src }}"
    git_org: "{{ item.git_org }}"
    git_repo: "{{ item.repo_target }}"
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_domain: "{{ gitea_domain }}"
    git_remote: "gitea"
  loop:
  - { repo_target: "{{ demo_auto_remediation_repo_name }}-awx", repo_src: "{{ role_path }}/files/repos/ace-demo-canary-awx", git_org: "{{ demo_auto_remediation_org }}" }
  - { repo_target: "{{ demo_auto_remediation_repo_name }}-docs", repo_src: "{{ role_path }}/files/repos/ace-demo-canary-docs", git_org: "{{ demo_auto_remediation_org }}" }
  when: new_repo_created is defined and new_repo_created == true

- name: Source Gitea endpoint
  include_role:
    name: gitea
    tasks_from: source-endpoints

- include_role:
    name: app-simplenode
  vars:
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_endpoint: "{{ gitea_internal_endpoint | regex_replace(\"http://\") }}"
    git_org_name: "{{ demo_auto_remediation_org }}"
    repo_name: "{{ demo_auto_remediation_repo_name }}"
  when: new_repo_created is defined and new_repo_created == true

# Include use case specific Jenkins values
- set_fact:
    include_jenkins_value_file: "{{ role_path }}/templates/demo-autorem-jobs.yml.j2"

- include_role:
    name: jenkins
    tasks_from: template-values-file
  vars:
    git_username: "{{ gitea_username }}"
    git_token: "{{ gitea_access_token }}"
    demo_repo: "{{ demo_auto_remediation_repo_name }}"
    demo_org: "{{ demo_auto_remediation_org }}"
    demo_jenkins_folder: "{{ demo_auto_remediation_folder }}"
    git_domain: "gitea.{{ ingress_domain }}"

# Create AWX secret before Jenkins so AWX credentials can be configured in Jenkins
- include_role:
    name: awx
    tasks_from: create-secrets

- include_role:
    name: jenkins

- include_role:
    name: awx

- include_tasks:
    file: configure-awx.yml

# Include use case specific Dashboard values
- set_fact:
    include_dashboard_value_file: "{{ role_path }}/templates/demo-auto-remediation-ansible-dashboard.yml.j2"

- include_role:
    name: dashboard
    tasks_from: template-values-file

- include_role:
    name: dashboard

# Trigger use case at the very end to make sure all tools are available
- include_tasks:
    file: trigger-use-case.yml
