# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_role:
    name: jenkins
    tasks_from: source-secret
  when: jenkins_username is not defined or jenkins_api_token is not defined

- set_fact:
    jenkins_build_url: "{{ ingress_protocol }}://{{ jenkins_domain }}/job/{{ jenkins_job_path.lstrip('/').rstrip('/') | urlencode }}/build?delay=0sec"
    jenkins_build_json_body: "{\"parameter\": {{ parameters | default([]) | to_json }} }"

- name: "Build {{ jenkins_job_path }}"
  ansible.builtin.uri:
    url: "{{ jenkins_build_url }}"
    method: POST
    url_username: "{{ jenkins_username }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
    body_format: form-urlencoded
    body:
      json: "{{ jenkins_build_json_body | to_json }}"
    status_code: 201
  register: build_trigger_result

- name: Print Trigger result
  debug:
    msg: "Jenkins Trigger result: {{ build_trigger_result }}"

- name: Extract Jenkins queue item URL
  set_fact:
    jenkins_queue_item_url: "{{ build_trigger_result.location }}api/json"

- name: Print Jenkins queue item URL
  debug:
    msg: "Jenkins queue item URL: {{ jenkins_queue_item_url }}"

- name: Wait for 1 minute before checking queue item
  ansible.builtin.wait_for:
    timeout: 60  # 1 minute

- name: Query Jenkins queue item
  ansible.builtin.uri:
    url: "{{ jenkins_queue_item_url }}"
    method: GET
    url_username: "{{ jenkins_username }}"
    url_password: "{{ jenkins_api_token }}"
    force_basic_auth: true
    status_code: 200
  register: queue_item_result
  until: queue_item_result.json.executable.number is defined
  retries: 10
  delay: 10

- name: Set Jenkins build number
  set_fact:
    jenkins_build_number: "{{ queue_item_result.json.executable.number }}"

- name: Print Jenkins build number
  debug:
    msg: "Jenkins build number: {{ jenkins_build_number }}"

- name: Set Jenkins job URL
  set_fact:
    jenkins_job_url: "{{ ingress_protocol }}://{{ jenkins_domain }}/job/{{ jenkins_job_path.lstrip('/').rstrip('/') | urlencode }}/{{ jenkins_build_number }}/api/json"

- name: Print Jenkins job URL
  debug:
    msg: "Jenkins job URL: {{ jenkins_job_url }}"